set nocompatible
set backspace=2
set t_Co=256
colo torte
hi CursorLine cterm=none ctermbg=DarkMagenta ctermfg=White
syntax enable
set number
set ruler
set hlsearch
set cindent
set laststatus=2
set mouse=a
